<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from nihrbackbone/xml/schema/CRM/Nihrbackbone/NbrStudyResearcher.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:949b32a86707c221427f42ad2b4f50b4)
 */

/**
 * Database access object for the NbrStudyResearcher entity.
 */
class CRM_Nihrbackbone_DAO_NbrStudyResearcher extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_nbr_study_researcher';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique NbrStudyResearcher ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to Contact
   *
   * @var int
   */
  public $researcher_contact_id;

  /**
   * FK to Campaign
   *
   * @var int
   */
  public $nbr_study_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_nbr_study_researcher';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'researcher_contact_id', 'civicrm_contact', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'nbr_study_id', 'civicrm_campaign', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Nihrbackbone_ExtensionUtil::ts('Unique NbrStudyResearcher ID'),
          'required' => TRUE,
          'where' => 'civicrm_nbr_study_researcher.id',
          'table_name' => 'civicrm_nbr_study_researcher',
          'entity' => 'NbrStudyResearcher',
          'bao' => 'CRM_Nihrbackbone_DAO_NbrStudyResearcher',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
        ],
        'researcher_contact_id' => [
          'name' => 'researcher_contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Nihrbackbone_ExtensionUtil::ts('FK to Contact'),
          'where' => 'civicrm_nbr_study_researcher.researcher_contact_id',
          'table_name' => 'civicrm_nbr_study_researcher',
          'entity' => 'NbrStudyResearcher',
          'bao' => 'CRM_Nihrbackbone_DAO_NbrStudyResearcher',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
        ],
        'nbr_study_id' => [
          'name' => 'nbr_study_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Nihrbackbone_ExtensionUtil::ts('FK to Campaign'),
          'where' => 'civicrm_nbr_study_researcher.nbr_study_id',
          'table_name' => 'civicrm_nbr_study_researcher',
          'entity' => 'NbrStudyResearcher',
          'bao' => 'CRM_Nihrbackbone_DAO_NbrStudyResearcher',
          'localizable' => 0,
          'FKClassName' => 'CRM_Campaign_DAO_Campaign',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'nbr_study_researcher', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'nbr_study_researcher', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
