<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2019
 *
 * Generated from /var/www/html/nbrdev/sites/default/files/civicrm/ext/nihrbackbone/xml/schema/CRM/Nihrbackbone/NihrStudy.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:0e4113ce339c76ed4cd01c1f600cfa91)
 */

/**
 * Database access object for the NihrStudy entity.
 */
class CRM_Nihrbackbone_DAO_NihrStudy extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_nihr_study';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique NihrStudy ID
   *
   * @var int unsigned
   */
  public $id;

  /**
   * Specific Study Number in NIHR BioResource
   *
   * @var string
   */
  public $study_number;

  /**
   * FK to Contact for Principal Investigator
   *
   * @var int unsigned
   */
  public $investigator_id;

  /**
   * Study Short Name
   *
   * @var string
   */
  public $short_name;

  /**
   * Study Long Name
   *
   * @var string
   */
  public $long_name;

  /**
   * Study Description
   *
   * @var text
   */
  public $description;

  /**
   * Ethics Number
   *
   * @var string
   */
  public $ethics_number;

  /**
   * Ethics Approved
   *
   * @var int unsigned
   */
  public $ethics_approved_id;

  /**
   * Ethics Approved Date
   *
   * @var date
   */
  public $ethics_approved_date;

  /**
   * Requirements
   *
   * @var text
   */
  public $requirements;

  /**
   * Study valid start date
   *
   * @var date
   */
  public $valid_start_date;

  /**
   * Study valid end date
   *
   * @var date
   */
  public $valid_end_date;

  /**
   * FK to Contact for Study Centre Origin
   *
   * @var int unsigned
   */
  public $centre_study_origin_id;

  /**
   * Notes
   *
   * @var text
   */
  public $notes;

  /**
   * Study Status
   *
   * @var string
   */
  public $status_id;

  /**
   * Date Created
   *
   * @var datetime
   */
  public $created_date;

  /**
   * FK to Contact for Created By
   *
   * @var int unsigned
   */
  public $created_by_id;

  /**
   * Date Modified
   *
   * @var datetime
   */
  public $modified_date;

  /**
   * FK to Contact for Modified By
   *
   * @var int unsigned
   */
  public $modified_by_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_nihr_study';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static ::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'investigator_id', 'civicrm_contact', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'centre_study_origin_id', 'civicrm_contact', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'created_by_id', 'civicrm_contact', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'modified_by_id', 'civicrm_contact', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Study ID'),
          'description' => ts('Unique NihrStudy ID'),
          'required' => TRUE,
          'table_name' => 'civicrm_nihr_study',
          'entity' => 'NihrStudy',
          'bao' => 'CRM_Nihrbackbone_DAO_NihrStudy',
          'localizable' => 0,
        ],
        'study_number' => [
          'name' => 'study_number',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Study Number'),
          'description' => ts('Specific Study Number in NIHR BioResource'),
          'maxlength' => 24,
          'size' => CRM_Utils_Type::MEDIUM,
          'table_name' => 'civicrm_nihr_study',
          'entity' => 'NihrStudy',
          'bao' => 'CRM_Nihrbackbone_DAO_NihrStudy',
          'localizable' => 0,
        ],
        'investigator_id' => [
          'name' => 'investigator_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Principal Investigator ID'),
          'description' => ts('FK to Contact for Principal Investigator'),
          'table_name' => 'civicrm_nihr_study',
          'entity' => 'NihrStudy',
          'bao' => 'CRM_Nihrbackbone_DAO_NihrStudy',
          'localizable' => 0,
        ],
        'short_name' => [
          'name' => 'short_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Study Short Name'),
          'description' => ts('Study Short Name'),
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'table_name' => 'civicrm_nihr_study',
          'entity' => 'NihrStudy',
          'bao' => 'CRM_Nihrbackbone_DAO_NihrStudy',
          'localizable' => 0,
        ],
        'long_name' => [
          'name' => 'long_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Study Long Name'),
          'description' => ts('Study Long Name'),
          'maxlength' => 256,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_nihr_study',
          'entity' => 'NihrStudy',
          'bao' => 'CRM_Nihrbackbone_DAO_NihrStudy',
          'localizable' => 0,
        ],
        'description' => [
          'name' => 'description',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => ts('Study Description'),
          'description' => ts('Study Description'),
          'rows' => 4,
          'cols' => 60,
          'table_name' => 'civicrm_nihr_study',
          'entity' => 'NihrStudy',
          'bao' => 'CRM_Nihrbackbone_DAO_NihrStudy',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
        ],
        'ethics_number' => [
          'name' => 'ethics_number',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Ethics Number'),
          'description' => ts('Ethics Number'),
          'maxlength' => 32,
          'size' => CRM_Utils_Type::MEDIUM,
          'table_name' => 'civicrm_nihr_study',
          'entity' => 'NihrStudy',
          'bao' => 'CRM_Nihrbackbone_DAO_NihrStudy',
          'localizable' => 0,
        ],
        'ethics_approved_id' => [
          'name' => 'ethics_approved_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Ethics Approved'),
          'description' => ts('Ethics Approved'),
          'table_name' => 'civicrm_nihr_study',
          'entity' => 'NihrStudy',
          'bao' => 'CRM_Nihrbackbone_DAO_NihrStudy',
          'localizable' => 0,
        ],
        'ethics_approved_date' => [
          'name' => 'ethics_approved_date',
          'type' => CRM_Utils_Type::T_DATE,
          'title' => ts('Ethics Approved Date'),
          'description' => ts('Ethics Approved Date'),
          'table_name' => 'civicrm_nihr_study',
          'entity' => 'NihrStudy',
          'bao' => 'CRM_Nihrbackbone_DAO_NihrStudy',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDate',
          ],
        ],
        'requirements' => [
          'name' => 'requirements',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => ts('Requirements'),
          'description' => ts('Requirements'),
          'rows' => 4,
          'cols' => 60,
          'table_name' => 'civicrm_nihr_study',
          'entity' => 'NihrStudy',
          'bao' => 'CRM_Nihrbackbone_DAO_NihrStudy',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
        ],
        'valid_start_date' => [
          'name' => 'valid_start_date',
          'type' => CRM_Utils_Type::T_DATE,
          'title' => ts('Valid Start Date'),
          'description' => ts('Study valid start date'),
          'table_name' => 'civicrm_nihr_study',
          'entity' => 'NihrStudy',
          'bao' => 'CRM_Nihrbackbone_DAO_NihrStudy',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDate',
          ],
        ],
        'valid_end_date' => [
          'name' => 'valid_end_date',
          'type' => CRM_Utils_Type::T_DATE,
          'title' => ts('Valid End Date'),
          'description' => ts('Study valid end date'),
          'table_name' => 'civicrm_nihr_study',
          'entity' => 'NihrStudy',
          'bao' => 'CRM_Nihrbackbone_DAO_NihrStudy',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDate',
          ],
        ],
        'centre_study_origin_id' => [
          'name' => 'centre_study_origin_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Study Origin Centre'),
          'description' => ts('FK to Contact for Study Centre Origin'),
          'table_name' => 'civicrm_nihr_study',
          'entity' => 'NihrStudy',
          'bao' => 'CRM_Nihrbackbone_DAO_NihrStudy',
          'localizable' => 0,
        ],
        'notes' => [
          'name' => 'notes',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => ts('Notes'),
          'description' => ts('Notes'),
          'rows' => 4,
          'cols' => 60,
          'table_name' => 'civicrm_nihr_study',
          'entity' => 'NihrStudy',
          'bao' => 'CRM_Nihrbackbone_DAO_NihrStudy',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
        ],
        'status_id' => [
          'name' => 'status_id',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Study Status'),
          'description' => ts('Study Status'),
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'table_name' => 'civicrm_nihr_study',
          'entity' => 'NihrStudy',
          'bao' => 'CRM_Nihrbackbone_DAO_NihrStudy',
          'localizable' => 0,
        ],
        'created_date' => [
          'name' => 'created_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Date Created'),
          'description' => ts('Date Created'),
          'table_name' => 'civicrm_nihr_study',
          'entity' => 'NihrStudy',
          'bao' => 'CRM_Nihrbackbone_DAO_NihrStudy',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ],
        ],
        'created_by_id' => [
          'name' => 'created_by_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Created By'),
          'description' => ts('FK to Contact for Created By'),
          'table_name' => 'civicrm_nihr_study',
          'entity' => 'NihrStudy',
          'bao' => 'CRM_Nihrbackbone_DAO_NihrStudy',
          'localizable' => 0,
        ],
        'modified_date' => [
          'name' => 'modified_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Date Modified'),
          'description' => ts('Date Modified'),
          'table_name' => 'civicrm_nihr_study',
          'entity' => 'NihrStudy',
          'bao' => 'CRM_Nihrbackbone_DAO_NihrStudy',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ],
        ],
        'modified_by_id' => [
          'name' => 'modified_by_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Modified By'),
          'description' => ts('FK to Contact for Modified By'),
          'table_name' => 'civicrm_nihr_study',
          'entity' => 'NihrStudy',
          'bao' => 'CRM_Nihrbackbone_DAO_NihrStudy',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'nihr_study', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'nihr_study', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
